# Generated by Django 3.0.1 on 2019-12-31 11:01

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_data',
            field=models.FileField(default='fasdf', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps/'),
            preserve_default=False,
        ),
    ]
