# Generated by Django 3.0.1 on 2019-12-31 11:08

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_map_map_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_data',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps/'),
        ),
    ]
