# Generated by Django 2.2.6 on 2019-12-31 13:21

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191231_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='video',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='videos/'),
        ),
    ]
